### ISSUE TITLE
Corrija seu .gitignore

### ISSUE THREAD

**Issue by acenelio** [danielbortolozo/spring-boot-clientes#2]
O conteúdo do seu arquivo .gitignore está incorreto. Aparentemente foi apagado todo conteúdo requerido para um projeto Spring Boot. Repare que as pastas .settings e target estão sendo salvas, o que não deveria estar acontecendo.

Para corrigir isto, você vai precisar trocar o conteúdo do seu .gitignore, depois delete essas duas pastas do seu projeto e salve um novo commit.

Use este .gitignore como modelo:

https://github.com/devsuperior/sds1-wmazoni/blob/master/backend/.gitignore

**Comment by danielbortolozo** [comment]
Valeu professor pela correção. Correção feita. Verifica se ficou certo.
